---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Sydney
    type: deployer
    target:
      region_id: ibm:yp:au-syd
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      echo -e "Creating services if needed..."
      cf create-service weatherinsights Free multiregion_weatherinsights
      cf create-service cloudantNoSQLDB Lite multiregion_cloudant
      cf push "${CF_APP}"
  - name: London
    type: deployer
    target:
      region_id: ibm:yp:eu-gb
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      echo -e "Creating services if needed..."
      cf create-service weatherinsights Free multiregion_weatherinsights
      cf create-service cloudantNoSQLDB Lite multiregion_cloudant
      cf push "${CF_APP}"
  - name: Dallas
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      echo -e "Creating services if needed..."
      cf create-service weatherinsights Free multiregion_weatherinsights
      cf create-service cloudantNoSQLDB Lite multiregion_cloudant
      cf push "${CF_APP}"
